spring:
  application:
    name: students-cli


logging:
  level:
    com.javmb.studentscli: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


app:
  mark:
    min: 0.0
    max: 10.0
  validation:
    enabled: true
  files:
    students-csv: data/students.csv
    students-xml: data/students.xml
    students-avg-xml: data/students_with_average.xml
